
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ZsomborJános
 */
public class Main_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Main_Frame
     */
    public Main_Frame() {
        
        
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        initComponents();
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        
            int width_Size = (int) tk.getScreenSize().getWidth();
            int height_Size = (int) tk.getScreenSize().getHeight();
        
         this.setSize(width_Size, height_Size);   
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_Menu = new javax.swing.JPanel();
        jButton_Teams_Overwiew = new javax.swing.JButton();
        jButton_Matches_Overview = new javax.swing.JButton();
        jButton_Team_Quiz = new javax.swing.JButton();
        jButton_Favourite_Team = new javax.swing.JButton();
        jButton_Top_Scorers = new javax.swing.JButton();
        jLabel_Welcome_1 = new javax.swing.JLabel();
        jLabel_Welcome_2 = new javax.swing.JLabel();
        jButton_Quit = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_Menu.setBackground(new java.awt.Color(0, 0, 204));

        jButton_Teams_Overwiew.setText("Csapatok áttekintése");
        jButton_Teams_Overwiew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Teams_OverwiewActionPerformed(evt);
            }
        });

        jButton_Matches_Overview.setText("Mérkőzések áttekintése");

        jButton_Team_Quiz.setText("Csapatismeret");
        jButton_Team_Quiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Team_QuizActionPerformed(evt);
            }
        });

        jButton_Favourite_Team.setText("Kedvenc csapat");

        jButton_Top_Scorers.setText("Legeredményesebb játékosok");

        jLabel_Welcome_1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Welcome_1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Welcome_1.setText("Üdvözlünk az UEFA Campions League Fan Softwareben!");

        jLabel_Welcome_2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel_Welcome_2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Welcome_2.setText("Kérjük válassz az alábbi menüpontok közül!");

        jButton_Quit.setText("Kilépés");
        jButton_Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_QuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_MenuLayout = new javax.swing.GroupLayout(panel_Menu);
        panel_Menu.setLayout(panel_MenuLayout);
        panel_MenuLayout.setHorizontalGroup(
            panel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_MenuLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(panel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Welcome_1)
                    .addComponent(jLabel_Welcome_2)
                    .addGroup(panel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton_Quit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Top_Scorers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Favourite_Team, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Team_Quiz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Teams_Overwiew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Matches_Overview, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(689, Short.MAX_VALUE))
        );
        panel_MenuLayout.setVerticalGroup(
            panel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_MenuLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel_Welcome_1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Welcome_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Teams_Overwiew)
                .addGap(24, 24, 24)
                .addComponent(jButton_Matches_Overview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Team_Quiz)
                .addGap(18, 18, 18)
                .addComponent(jButton_Favourite_Team)
                .addGap(18, 18, 18)
                .addComponent(jButton_Top_Scorers)
                .addGap(18, 18, 18)
                .addComponent(jButton_Quit)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Team_QuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Team_QuizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Team_QuizActionPerformed

    private void jButton_QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QuitActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton_QuitActionPerformed

    private void jButton_Teams_OverwiewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Teams_OverwiewActionPerformed
        // TODO add your handling code here:
        panel_Menu.setVisible(false);
    }//GEN-LAST:event_jButton_Teams_OverwiewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        //Image_Panel panel_Menu = new Image_Panel(new ImageIcon("images/Main_image."));
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Frame().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Favourite_Team;
    private javax.swing.JButton jButton_Matches_Overview;
    private javax.swing.JButton jButton_Quit;
    private javax.swing.JButton jButton_Team_Quiz;
    private javax.swing.JButton jButton_Teams_Overwiew;
    private javax.swing.JButton jButton_Top_Scorers;
    private javax.swing.JLabel jLabel_Welcome_1;
    private javax.swing.JLabel jLabel_Welcome_2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_Menu;
    // End of variables declaration//GEN-END:variables
}
